name: gatekeeper_app
description: "Smart Gatekeeper Tenant Smart Key Application (Flutter Hybrid Thin Client + WebView)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  permission_handler: ^11.3.1
  http: ^1.2.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  flutter_foreground_task: ^6.2.0
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.3
  flutter_beacon:
    path: ./android/app/libs/flutter_beacon_local

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
